### ISSUE TITLE
Digi-Key part numbers for lines 22 to 26 of the AP Hand Controller Parts List

### ISSUE THREAD

**Issue by ab15Kath** [cytan299/ap_hand_controller#1]
Attn. cytan,
Could you kindly provide a Part # for the following lines of your bill of materials list:
LINE 22: 	0805 surface mount 100 ohm resistor
LINE 23:  	1206 surface mount 0.1 uF ceramic capacitor
LINE 24:	Axial electrolytic capacitor 10uF, 50V
LINE 25:	10 kohm resistor, ¼ W
LINE 26:	50 ohm, ¼ W
Thanks,
Andrew
abrenyo@rogers.com

**Comment by cytan299** [comment]
Hi Andrew,
   The above parts are really generic. Any vendor will do on Digikey. I bought surface mount caps and resistor kits and selected the parts out from my kits, so I don't have any part numbers.

   So are you planning to build the hand controller?

cytan

**Comment by ab15Kath** [comment]
Hi cytan,Thank you for responding!Yes, I am buying the parts as we email.I  like the hand held feeling of a controller rather than a mobile phone.I am not very good at electronics but I had a good look at all the work you did in providing excellent directions and material so I am confident in assembling the controller.I would really appreciate it if you wouldn't mind picking the generic parts for me to make it fool proof for me - I have never selected electronic parts before and my order is stalled at those parts. There are something like a few thousand choices for one item alone. I don't know what to select. I hope that it's not too much work.The rest has all been ordered.I am really looking forward to this project as there are isn't much stargazing with the weather in Ontario, Canada.Many thanks for your design - I have an AP1100 as my retirement endeavour and I am slowly building my setup over a few years.Andrew Brenyo

Sent from Rogers Yahoo Mail on Android 
 
  On Tue, Jan 5, 2021 at 9:33 PM, cytan299<notifications@github.com> wrote:   


Hi Andrew,
The above parts are really generic. Any vendor will do on Digikey. I bought surface mount, caps and resistor kits and selected the parts out from my kits, so I don't have any part numbers.

So are you planning to build the hand controller?

cytan

**Comment by cytan299** [comment]
I'll send you the part numbers tomorrow.

**Comment by cytan299** [comment]
I've updated the BOM to include the missing Digikey part numbers. 

Also, FYI, I use the hand controller with both my AP1100AE and Mach1GTO and it works great with PoleMaster or SharpCap for Polar Alignment.

**Comment by ab15Kath** [comment]
Hi cytan,

Fantastic, thank you so much for your help. I will finish my order tonight and hopefully put it together in a few weeks once all the parts are in.

I will also keep in mind using PoleMaster or SharpCap for Polar Alignment once I get there.

A Happy New Year to you and your family and a safe 2021,

Andrew Brenyo
