### ISSUE TITLE
Power-up issue

### ISSUE THREAD

**Issue by ab15Kath** [cytan299/ap_hand_controller#2]
Hi C.Y.Tan,

The Simple A-P Hand Controller that you designed is wonderful. I really like the in-the-hand feel and the fine control of the thumb joystick.
Now that I have built the hand controller I am truly amazed by all the work you put into it!
I have only one issue to get it fully functional. I cannot get it to power-on once I plug it into the GTOCP4 box. The yellow LED2 turns on and stays on, but the SparkFun Pro Micro power LED does not light up or the OLED. However, once I connect a micro USB to the Pro Micro board the power LED lights up and I am able to move my GTO1100 mount. The yellow LED2 turns off when the micro USB is used to power the hand controller PCB.  
Is it a hardware or software problem? I triple checked all of my soldered connections and your Sketch loaded from Arduino flawlessly. I connected the hand controller PCB to a 12 volt battery and, once again, only the yellow LED2 would light up and stay on. What am I not understanding – do I need to initialize/turn on something on the mount? I have no PCB programming experience.
I am completely stumped as to how to power-up the hand controller from the mount. I would appreciate any help that you can provide.
Here is my setup:
1.	The dedicated power source for the mount is a Pyramid 12 Volt DC converter.
2.	I use APCC to control my mount, firmware version VCP4-P02-08 (latest version). 
3.	I installed the SparkFun drivers to Arduino prior to loading the sketch.
4.	I use RASPA for polar alignment, but I would like to learn how to use PoleMaster.
5.	I’ve included four photos of the PCB - just in case some hardware is missing.  

Thanks,
Andrew Brenyo
![IMG_20210313_111612194_HDR](https://user-images.githubusercontent.com/63481575/111037813-d643ef00-83f3-11eb-931e-29ebd842c3db.jpg)
![IMG_20210313_111632717](https://user-images.githubusercontent.com/63481575/111037815-d7751c00-83f3-11eb-950d-7175a4a92566.jpg)
![IMG_20210313_111739128](https://user-images.githubusercontent.com/63481575/111037817-d80db280-83f3-11eb-92da-a1fd8eb65955.jpg)
![IMG_20210313_111925392_HDR](https://user-images.githubusercontent.com/63481575/111037819-d8a64900-83f3-11eb-899f-389f2fb5b7d7.jpg)

**Comment by cytan299** [comment]
Thanks for your kind words.

Since everything works when powered via the USB port, this means that when you connect the hand controller to CP4, it's not getting power.

You'll need to check the following with a voltmeter

1.  12 V is getting into the board after you plug it into the CP4. Check pin 1 of the J2 header. It should read 12 V. If it doesn't read 12 V, the cable that you made is not correct. See slide 10. Make sure the 12 V wire is soldered to the connector.
2. Check that 3.3 V regulator (U2) is spitting out 3.3V. There are 3 pins on the regulator (R78E3.3), one of them should be 12 V, the middle one is ground and the other should be 3.3 V.
3. Finally, the arduino Pro Micro should see 3.3V. Check pin 21 of the Pro Micro. If it is not 3.3V then there could be an open between the Pro Micro and the regulator.

My bet is that you didn't wire the cable that connects the CP4 to the controller correctly. Post a followup whether that's the problem or not.

cytan

**Comment by ab15Kath** [comment]
Hi cytan,

I followed through on your suggestions and was able to power-up the hand controller from the mount.
However, the solution turned out to be something completely unexpected – at least from my novice point of view. 
1.	I checked Pin 6 (12VIN) of the J2 header and Pin 1 (GND) and had a reading of 13.74 volts using a voltmeter. So the PCB was getting enough power.
2.	The 3.3V regulator was working fine too, with the IN side showing a reading above 12 volts and the OUT side showing a reading of 3.28 volts.
3.	Your suggestion to check Pin 21 (VCC) was a good idea, it only read ~1.27 volts. There may be an opening/break from the R2 to the Max3232CSE chip, but I have not checked that far yet.  
Photo 3630: Hand Controller PCB turned on and fully functional with power from the mount – all commands work properly.
Photo 7888: Jumper cable from LED 2 (positive side) to Pin 21 (VCC). The hand controller powered-up fully once connected to the mount using this wiring. 
Photo 2356: Showing the orientation of the LEDs. Both were checked with a 3.5 volt battery pack and lit up properly. I checked the 1000 resistors at either end of their connections and, once again, the LEDs lit up. Confirming the connections are good. Don’t mind the messy connections I did a re-solder of many of the components just in case there was a poor connection somewhere.
Photo 5299: The CP4 connector with the wires matching Slide 10. Again, the wiring is a bit messy as I tried different combinations. I tried the connector without the yellow wire soldered and then with only the green wire soldered to see if it would make a difference and had no success.
The jumper wiring was a surprise as I tested each connection, and although it works, I would appreciate a better or possibly the correct wiring solution. I am a bit concerned that I will burn out or melt my board by bypassing R2. With my lack of experience I’m afraid that I might fry the Pro Micro board if I try too many solutions. 

Thanks,
Andrew   
![IMG_20210314_115443630](https://user-images.githubusercontent.com/63481575/112706382-2dc56e80-8e7a-11eb-876c-5082c3054c7e.jpg)
![IMG_20210314_122757888](https://user-images.githubusercontent.com/63481575/112706385-2f8f3200-8e7a-11eb-82d6-78e52184f6cc.jpg)
![IMG_20210314_140522356](https://user-images.githubusercontent.com/63481575/112706387-30c05f00-8e7a-11eb-939e-499614b1d8be.jpg)
![IMG_20210314_162455299](https://user-images.githubusercontent.com/63481575/112706388-3158f580-8e7a-11eb-9fd5-8658eccfcfc1.jpg)
![IMG_20210314_122757888](https://user-images.githubusercontent.com/63481575/112706392-39189a00-8e7a-11eb-91be-7a844d9b6dde.jpg)
![IMG_20210314_140522356](https://user-images.githubusercontent.com/63481575/112706398-3f0e7b00-8e7a-11eb-97ab-69576ebe9efd.jpg)
![IMG_20210314_162455299](https://user-images.githubusercontent.com/63481575/112706427-6b29fc00-8e7a-11eb-903d-397de0388933.jpg)
